kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  LOGLEVEL: {{ .Values.configmap.loglevel | quote }}
  PERSIST: {{ .Values.configmap.persist | quote}}
  DBNAME: {{ .Values.configmap.dbname | quote }}