apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert.name }}
  namespace: {{ .Values.cert.nspace }}
spec:
  acme:
    server: {{ .Values.cert.server.prod }}
    email: {{ .Values.cert.email }}
    privateKeySecretRef:
      name: {{ .Values.cert.privKeyName }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}