apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echoapp.fullname" . }}
  labels:
    {{- include "echoapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echoapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echoapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
              protocol: TCP
          env:
            - name: MONGODBURL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: mongo-db-url 
            - name: LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name  }}
                  key: LOGLEVEL
            - name: PERSIST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name  }}
                  key: PERSIST
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name  }}
                  key: DBNAME
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
