# Default values for echo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: eu.gcr.io/develeap-bootcamp/echo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

app:
  temp-var: something
  containerPort: 3000

secret:
  name: echo-mongodb-secret
  url: mongodb://user:password@mongo-service/echo?authSource=echo&ReplicaSet=MainRepSet

configmap:
  name: echo-config-map
  persist: "True"
  loglevel: info
  dbname: echo

service:
  type: ClusterIP
  port: 80

cert:
  name: letsencrypt-issue
  nspace: cert-manager
  isStaging: true
  server:
    prod: https://acme-v02.api.letsencrypt.org/directory
    stage: https://acme-staging-v02.api.letsencrypt.org/directory
  email: ofer.rvd@gmail.com
  privKeyName: secret-tls

cleaner:
  name: "mongo-cleaner"
  restartPolicy: OnFailure
  backoffLimit: 6
  schedule: "0 0 * * *"

StorageClass:
  name: &scname "slow"
  provisioner: kubernetes.io/gce-pd
  gcp:
    type: pd-standard
    fstype: xfs
  replicationtype: none

ingress:
  name: tls-ingress
  className: "nginx"
  host: lookwhostalking2.tk

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

mongodb:
  architecture: replicaset
  useStatefulSet: true
  auth:
    rootPassword: "password"
    username: "user"
    password: "password"
    database: "echo"
    replicaSetKey: "cmVwbFNldEtleQ=="
  replicaSetName: MainRepSet
  replicaCount: 3
  service:
    nameOverride: "mongo-service"
    clusterIP: "None"
  persistence:
    storageClass: *scname
    size: 1Gi
  arbiter:
    enabled: false
